# start with `docker compose up`
services:
  free-games-claimer:
    container_name: fgc
    image: ghcr.io/gabrielbryk/free-games-claimer
    build: .
    healthcheck:
      test: pgrep bun && curl --fail http://localhost:6080 || exit 1
      interval: 5s
      timeout: 5s
    ports:
      # - "5900:5900" # VNC server
      - "6080:6080" # noVNC (browser-based VNC client)
    volumes:
      - fgc:/fgc/data
    # command: bun run epic-games.ts
    environment:
      # - EMAIL=foo@bar.org
      # - NOTIFY='tgram://...'

volumes:
  fgc:
